services:
  postgres:
    image: postgres:17-alpine3.20
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: 53cret
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.6
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: 53cret
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME_PORT: 7080
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7080/health/ready" ]
      interval: 15s
      timeout: 2s
      retries: 15
    command:
      - start-dev
      - --import-realm
    ports:
      - "7080:8080"
    expose:
      - "7080"
    depends_on:
      - postgres
    volumes:
      - ./keycloak/Greylian-realm.json/:/opt/keycloak/data/import/Greylian-realm.json
    networks:
      - local_network

volumes:
  postgres_data:
    driver: local
networks:
  local_network:
    driver: bridge

