server:
  port: 8080

spring:
  application:
    name: spring-boot-thymeleaf-keycloak
  docker:
    compose:
      enable: true
  security:
    oauth2:
      client:
        provider:
          Greylian:
            issuer-uri: http://localhost:7080/realms/Greylian
        registration:
          keycloak:
            provider: Greylian
            authorization-grant-type: authorization_code
            client-id: spring-boot-thymeleaf-keycloak
            client-secret: 5Lzi66sHd4YZnRQ03d2iCxsxyZG71FAz
            scope: openid

logging:
  level:
    org:
      springframework:
        security: DEBUG
        boot: INFO

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
